import { repoRelative } from '../../util/paths.js';

/** Comment syntax for the managed banner. JSON files use a "_generated" key instead. */
export type CommentStyle = 'md' | 'hash';

const NOTICE = 'GENERATED by ai-agent-setup — DO NOT EDIT. Run `ai-agent-setup build` to regenerate.';

/**
 * Build the "do not edit" banner placed at the top of every generated text file.
 * `sourceFiles` are absolute core paths; they are shown repo-relative.
 */
export function managedHeader(style: CommentStyle, sourceFiles: string[]): string {
  const sources = dedupe(sourceFiles.map((f) => repoRelative(f)));
  const lines = [NOTICE, ...(sources.length ? ['Sources:', ...sources.map((s) => `  - ${s}`)] : [])];

  if (style === 'md') {
    return `<!--\n${lines.join('\n')}\n-->`;
  }
  // hash style (shell, toml)
  return lines.map((l) => `# ${l}`).join('\n');
}

function dedupe(arr: string[]): string[] {
  return [...new Set(arr)];
}
