import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mapClaudeEvent } from '../../src/adapters/claude/event-map.js';
import { renderHooks } from '../../src/adapters/claude/hooks.js';
import { renderMcp } from '../../src/adapters/claude/mcp.js';
import type { CoreModel, Hook } from '../../src/core/model.js';
import { loadCore } from '../../src/core/load.js';
import { minimalCore } from '../helpers/paths.js';

function base(): CoreModel {
  return { instructions: [], agents: [], skills: [], hooks: [], mcpServers: [] };
}

test('event-map: each neutral trigger maps to the expected Claude event/matcher', () => {
  const mk = (trigger: Hook['trigger']): Hook => ({
    id: 't',
    scriptFile: '/core/hooks/t.sh',
    trigger,
    blocking: true,
    targets: [],
  });
  assert.deepEqual(mapClaudeEvent(mk('before-command')), {
    event: 'PreToolUse',
    matcher: 'Bash',
    extractFields: ['command'],
  });
  const fileAccess = mapClaudeEvent(mk('before-file-access'));
  assert.equal(fileAccess.event, 'PreToolUse');
  assert.ok(fileAccess.matcher?.includes('Read') && fileAccess.matcher?.includes('Bash'));
  assert.equal(mapClaudeEvent(mk('after-file-change')).event, 'PostToolUse');
  const stop = mapClaudeEvent(mk('before-finish'));
  assert.equal(stop.event, 'Stop');
  assert.equal(stop.matcher, undefined, 'Stop takes no matcher');
});

test('renderHooks: emits script + wrapper per hook and one settings.json merge target', () => {
  const { core } = loadCore(minimalCore); // one hook: guard (before-command, blocking)
  const files = renderHooks(core);
  const rel = files.map((f) => f.relativePath).sort();
  assert.deepEqual(rel, ['hooks/guard.sh', 'hooks/guard.wrapper.sh', 'settings.json']);

  const settings = files.find((f) => f.relativePath === 'settings.json')!;
  assert.equal(settings.managed, false, 'settings.json must be a merge target');
  const parsed = JSON.parse(settings.content);
  assert.ok(parsed.hooks.PreToolUse, 'guard wires under PreToolUse');
  assert.equal(parsed.hooks.PreToolUse[0].matcher, 'Bash');
  // No undocumented provenance keys in Claude-owned JSON.
  assert.equal(parsed._generated, undefined, 'settings.json must not contain _generated');
  assert.deepEqual(Object.keys(parsed), ['hooks'], 'settings.json holds only intended keys');
  // Provenance lives in GeneratedFile metadata instead.
  assert.deepEqual(settings.managedPaths, ['hooks.PreToolUse']);
  assert.equal(settings.mergeTarget, '~/.claude/settings.json');

  const wrapper = files.find((f) => f.relativePath === 'hooks/guard.wrapper.sh')!;
  assert.equal(wrapper.mode, 0o755);
  assert.ok(wrapper.content.includes('exit 2'), 'blocking hook maps to exit 2');

  const script = files.find((f) => f.relativePath === 'hooks/guard.sh')!;
  assert.equal(script.mode, 0o755);
  assert.ok(script.content.includes('GENERATED by ai-agent-setup'), 'banner injected');
});

test('renderHooks: command is CLAUDE_CONFIG_DIR-aware, quoted, and free of build-time HOME', () => {
  const { core } = loadCore(minimalCore);
  const settings = renderHooks(core).find((f) => f.relativePath === 'settings.json')!;
  const command: string = JSON.parse(settings.content).hooks.PreToolUse[0].hooks[0].command;
  assert.equal(command, '"${CLAUDE_CONFIG_DIR:-$HOME/.claude}/hooks/guard.wrapper.sh"');
  assert.ok(command.startsWith('"') && command.endsWith('"'), 'quoted for spaces');
  assert.ok(command.includes('${CLAUDE_CONFIG_DIR:-$HOME/.claude}'), 'uses runtime var');
  assert.ok(!command.includes(process.env.HOME ?? '\0'), 'no build-time absolute HOME embedded');
  assert.ok(!/\/Users\/|\/home\//.test(command), 'no absolute home path baked in');
});

test('renderHooks: non-blocking hook never maps to exit 2', () => {
  // renderHooks reads the script file from disk, so reuse the real fixture hook
  // but flip it to non-blocking to exercise the exit-code branch.
  const { core } = loadCore(minimalCore);
  const nonBlocking: Hook = { ...core.hooks[0]!, blocking: false, trigger: 'after-file-change' };
  core.hooks = [nonBlocking];
  const wrapper = renderHooks(core).find((f) => f.relativePath.endsWith('.wrapper.sh'))!;
  assert.ok(!wrapper.content.includes('exit 2'), 'non-blocking must not block');
});

test('renderMcp: excludes disabled servers and preserves ${VAR} refs', () => {
  const core = base();
  core.mcpServers = [
    { name: 'on', enabled: true, transport: 'stdio', command: 'npx', args: ['x'], env: { TOK: '${TOK}' }, sourceFile: 's.yaml' },
    { name: 'off', enabled: false, transport: 'stdio', command: 'npx', args: [], env: {}, sourceFile: 's.yaml' },
  ];
  const files = renderMcp(core);
  assert.equal(files.length, 1);
  const mcp = files[0]!;
  assert.equal(mcp.managed, false);
  // User-global target, not the project-scoped .mcp.json.
  assert.equal(mcp.relativePath, '.claude.json');
  assert.equal(mcp.root, 'home');
  assert.equal(mcp.mergeTarget, '~/.claude.json');
  assert.deepEqual(mcp.managedPaths, ['mcpServers.on']);
  const parsed = JSON.parse(mcp.content);
  assert.ok(parsed.mcpServers.on, 'enabled server present');
  assert.equal(parsed.mcpServers.off, undefined, 'disabled server omitted');
  assert.equal(parsed.mcpServers.on.env.TOK, '${TOK}', 'var ref preserved');
  assert.equal(parsed._generated, undefined, '.claude.json must not contain _generated');
  assert.deepEqual(Object.keys(parsed), ['mcpServers'], 'fragment holds only mcpServers');
});
