import { test } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { loadCore } from '../../src/core/load.js';
import { claudeAdapter } from '../../src/adapters/claude/index.js';
import { codexAdapter } from '../../src/adapters/codex/index.js';
import { projectRoot } from '../helpers/paths.js';

/**
 * Frontmatter-bearing files (SKILL.md, Claude subagent .md) MUST start with the
 * `---` block on line 1, or Claude/Codex silently fail to read name/description.
 * The provenance banner has to live below the frontmatter, not above it.
 */
const { core } = loadCore(path.join(projectRoot, 'core'));

test('codex SKILL.md starts with YAML frontmatter, banner below it', () => {
  const files = codexAdapter.render(core).files.filter((f) => f.relativePath.endsWith('SKILL.md'));
  assert.ok(files.length > 0, 'skills rendered');
  for (const f of files) {
    assert.ok(f.content.startsWith('---\n'), `${f.relativePath} must open with frontmatter`);
    const secondBlock = f.content.indexOf('\n---\n');
    assert.ok(secondBlock > 0, 'frontmatter is closed');
    assert.match(f.content, /^---\nname:/, 'name is in the leading frontmatter');
    // The generated banner still ships, just after the frontmatter.
    assert.ok(f.content.includes('GENERATED by ai-agent-setup'), 'provenance retained');
  }
});

test('claude SKILL.md and subagent .md start with frontmatter', () => {
  const files = claudeAdapter.render(core).files;
  const targets = files.filter(
    (f) => f.relativePath.endsWith('SKILL.md') || /agents\/.*\.md$/.test(f.relativePath),
  );
  assert.ok(targets.length > 0);
  for (const f of targets) {
    assert.ok(f.content.startsWith('---\n'), `${f.relativePath} must open with frontmatter`);
    assert.match(f.content, /^---\nname:/, `${f.relativePath} name in frontmatter`);
  }
});
